# 诱饵数量读取的位置 =======================
X1: 1736
X2: 1762
Y1: 970
Y2: 992

# 单次最大卖出价格 =========================
SINGLE_SELL_LIMIT: 20

# 抛竿时间 (单位: 秒)  ========================
THROWING_ROD_TIME: 0.5

# 展示钓上来的鱼的时间 (单位: 秒) ================
SHOW_FISH_TIME: 0.8

# 拉杆/松杆时间  (单位: 秒) =====================
# 5为满配重型鱼竿
# 3为轻型竹制鱼竿
PULL_TIME: 3.0 # 拉杆
RELEASE_TIME: 1 # 松杆

#  循环拉杆/松杆，把指针控制在一定范围内 (单位: 秒) ====
PULL_TIME_LOOP: 0.6 # 拉杆
RELEASE_TIME_LOOP: 0.05 # 松杆

# 钓鱼失败信息捕获 =========================
F_X1: 792
F_X2: 1129
F_Y1: 159
F_Y2: 214

# 卖出鱼价格信息捕获 =======================
S_X1: 1241
S_X2: 1748
S_Y1: 294
S_Y2: 767

# 预设的钓鱼次数 ==========================
FISHING_TIMES: -1

# 暂停按钮 ==============================
RUNNING_PAUSE_BTN: F8

# 关闭开启提示音 ==========================
SOUND: true

# 自动清理历史日志 =========================
LOG_AUTO_CLEANS_UP: true

# 加时开关，自动点击加时按钮 ==================
ADD_TIME: on

# 使用防脚本检测随机震荡指数 ==================
USING_OSCILLATION_INDEX: true

# 防脚本检测随机震荡指数 =====================
OSCILLATION_INDEX: 0.2

# 随机发送表情包的概率 ======================
SEND_EMO: 0.3

# 使用捕获窗口 (需要使用窗口的句柄，据说不安全) ======
#USE_WIN_CAPTURE: 猛兽派对
# 保存位置
DATA_PATH: "data.xlsx"

QUALITY:
  - 传奇
  - 史诗
  - 稀有
  - 非凡
  - 标准

CATEGORY:
- 甲方满意鱼
- 拟岩鱼
- 辐射鲈
- 地包天鱼
- 黄鸭叫
- 幻光鱼
- 芭蕾蓬蓬鱼
- 保洁鱼
- 骗子鱼
- 光斑鱼
- 平凡鱼
- 狗头鱼
- 海底豚
- 流浪剑客
- 美髯公
- 呆呆鲶
- 牡丹鱼
- 烟花鱼
- 拷贝鱼
- 教练鱼
- 冰河鲟
- 熔岩鱼
- 雷鳗
- 发财鲤
- 果冻鱼
- 大师龟
- 狼蛛蟹
- 拳击虾
- 蝌蚪宝宝
- 大蝌蚪
- 幼蛙
- 青蛙
- 金蛙
- 粉丝虾
- 夜明珠
- 娃娃鱼
- 奇怪的东西
- 钱袋
- 戒指
- 不明化石